# Use a minimal Java runtime image
FROM eclipse-temurin:17-jre

# Set the working directory
WORKDIR /app

# Copy your built JAR file into the container
COPY target/myapp.jar /app/myapp.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "/app/myapp.jar"]
